const List<String> arabCountries = [
  'EG',
  'SA',
  'AE',
  'KW',
  'QA',
  'OM',
  'BH',
  'JO',
  'LB',
  'IQ',
  'MA',
  'DZ',
  'TN',
  'LY',
  'SD',
  'YE',
  'SY',
  'PS',
  'MR',
  'DJ',
  'SO',
  'KM',
];

String getCountryFromCode(String code) {
  const countryMap = {
    '+20': 'egypt',
    '+966': 'saudi',
    '+971': 'uae',
    '+965': 'kuwait',
    '+974': 'qatar',
    '+973': 'bahrain',
    '+968': 'oman',
    '+962': 'jordan',
    '+961': 'lebanon',
    '+964': 'iraq',
    '+212': 'morocco',
    '+213': 'algeria',
    '+216': 'tunisia',
    '+970': 'palestine',
    '+963': 'syria',
    '+967': 'yemen',
    '+218': 'libya',
    '+249': 'sudan',
    '+222': 'mauritania',
    '+253': 'djibouti',
    '+269': 'comoros',
    '+252': 'somalia',
  };
  return countryMap[code] ?? 'egypt';
}