// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiZMBYjLHCzWmCsf4MjfTq6p2BGqVKjns',
    appId: '1:439084202195:web:dea8453bbccebb96e5fc26',
    messagingSenderId: '439084202195',
    projectId: 'planthub-409a9',
    authDomain: 'planthub-409a9.firebaseapp.com',
    storageBucket: 'planthub-409a9.firebasestorage.app',
    measurementId: 'G-Z8GWH9LZCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxu1uRWluUS-DN-lJ449iXDxTlAyL50Vs',
    appId: '1:439084202195:android:0bc1a2024cef54aae5fc26',
    messagingSenderId: '439084202195',
    projectId: 'planthub-409a9',
    storageBucket: 'planthub-409a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW6DtMPkYMrNDITwXqKKxuKBFmGqIbnHk',
    appId: '1:439084202195:ios:202ad89b15e1de0be5fc26',
    messagingSenderId: '439084202195',
    projectId: 'planthub-409a9',
    storageBucket: 'planthub-409a9.firebasestorage.app',
    iosBundleId: 'com.example.plantHubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW6DtMPkYMrNDITwXqKKxuKBFmGqIbnHk',
    appId: '1:439084202195:ios:202ad89b15e1de0be5fc26',
    messagingSenderId: '439084202195',
    projectId: 'planthub-409a9',
    storageBucket: 'planthub-409a9.firebasestorage.app',
    iosBundleId: 'com.example.plantHubApp',
  );
}
